Added sell-format option to format the values
BG-Software-LLC/WildChests pull request #73
Opened 2021-11-15 21:26 UTC by Faceless0102

2021-11-16 19:32 UTC, Faceless0102 commented
I run this version on my public server without issues

2021-11-16 20:22 UTC, OmerBenGera requested changes
Great job!
There needs to be some changes, please take a look at my comments

2021-11-16 20:22 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildchests/handlers/SettingsHandler.java
> +        sellFormat = cfg.getBoolean("sell-format", true);
sell_format should be disabled by default

2021-11-16 20:22 UTC, OmerBenGera commented on src/main/resources/config.yml
> +sell-format: true
Should be disabled by default

2021-11-16 20:22 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildchests/utils/StringUtils.java
> +    private static final double Q = 1000000000000000D, T = 1000000000000D, B = 1000000000D, M = 1000000D, K = 1000D;
Add _ to the numbers (especially the larger ones)
M will be 1_000_000 for example.

2021-11-16 20:22 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildchests/utils/StringUtils.java
> +    public static String format(double d){ return format(BigDecimal.valueOf(d)); }
Should not be one-line

2021-11-16 20:22 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildchests/utils/StringUtils.java
> +    public static String format(double d){ return format(BigDecimal.valueOf(d)); }
Should not be one-line

2021-11-16 20:22 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildchests/utils/StringUtils.java
> +    private static final double Q = 1000000000000000D, T = 1000000000000D, B = 1000000000D, M = 1000000D, K = 1000D;
Can be saved as longs instead of doubles.

2021-11-16 20:22 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildchests/task/NotifierTask.java
> +                    if(!plugin.getSettings().sellFormat)
The only difference in this if is how to format the parameter.
Instead, use the inline-if syntax

2021-11-16 20:22 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildchests/task/NotifierTask.java
> +                    if(!plugin.getSettings().sellFormat)
The only difference in this if is how to format the parameter.
Instead, use the inline-if syntax

2021-11-16 20:22 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildchests/task/NotifierTask.java
> +                if(!plugin.getSettings().sellFormat)
Same as above

2021-11-16 20:41 UTC, Faceless0102 commented
Great! I'm gonna fix these right now

2021-11-16 21:03 UTC, Faceless0102 commented
```java
C:\Users\Alex\IdeaProjects\WildChests\src\main\java\com\bgsoftware\wildchests\utils\StringUtils.java:11: error: integer number too large: 1000000000000000
    private static final long Q = 1_000_000_000_000_000, T = 1_000_000_000_000, B = 1_000_000_000, M = 1_000_000, K = 1_000;
                                  ^
C:\Users\Alex\IdeaProjects\WildChests\src\main\java\com\bgsoftware\wildchests\utils\StringUtils.java:11: error: integer number too large: 1000000000000
    private static final long Q = 1_000_000_000_000_000, T = 1_000_000_000_000, B = 1_000_000_000, M = 1_000_000, K = 1_000;

```

For the Q and T values it says the integer number is too large 😢

2021-11-16 21:42 UTC, Faceless0102 commented
Done, can you check please?

2021-11-17 17:49 UTC, OmerBenGera requested changes

2021-11-17 17:49 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildchests/utils/StringUtils.java
> +        double d = bigDecimal.longValue();
Converting BigDecimals to doubles can get you to lose data for large numbers.
I dont suspect it can happen, but I still prefer the checks to work with BigDecimal instead of double.

2021-11-17 17:49 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildchests/task/NotifierTask.java
> +                if(!plugin.getSettings().sellFormat) Locale.SOLD_CHEST_FOOTER.send(offlinePlayer.getPlayer(), StringUtils.format(totalEarned)); else Locale.SOLD_CHEST_FOOTER.send(offlinePlayer.getPla
This is not what I meant.
The last parameter should be in an inline if condition
(<condition> ? <true-case> : <false-case>)

2021-11-17 19:13 UTC, Faceless0102 commented on src/main/java/com/bgsoftware/wildchests/task/NotifierTask.java
> +                if(!plugin.getSettings().sellFormat) Locale.SOLD_CHEST_FOOTER.send(offlinePlayer.getPlayer(), StringUtils.format(totalEarned)); else Locale.SOLD_CHEST_FOOTER.send(offlinePlayer.getPla
Yeah I tried with inline if condition, but I got the following error:
What I tried:
`(plugin.getSettings().sellFormat == false) ? Locale.SOLD_CHEST_LINE.send(offlinePlayer.getPlayer(), item.amount, item.itemStack.getType(), StringUtils.format(item.amountEarned)) : Locale.SOLD_CHEST_LINE.send(offlinePlayer.getPlayer(), item.amount, item.itemStack.getType(), StringUtils.fancyFormat(item.amountEarned));`

Error: not a statement

2021-11-17 20:46 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildchests/task/NotifierTask.java
> +                if(!plugin.getSettings().sellFormat) Locale.SOLD_CHEST_FOOTER.send(offlinePlayer.getPlayer(), StringUtils.format(totalEarned)); else Locale.SOLD_CHEST_FOOTER.send(offlinePlayer.getPla
You need to do it on the last parameter and not the entire method.
Also, never do <condition> == false, instead, use !<condition>

2021-11-17 20:48 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildchests/task/NotifierTask.java
> +                if(!plugin.getSettings().sellFormat) Locale.SOLD_CHEST_FOOTER.send(offlinePlayer.getPlayer(), StringUtils.format(totalEarned)); else Locale.SOLD_CHEST_FOOTER.send(offlinePlayer.getPla
If you dont understand what I mean, leave it as it is and I will do it before merging.

2021-11-18 10:12 UTC, Faceless0102 commented on src/main/java/com/bgsoftware/wildchests/task/NotifierTask.java
> +                if(!plugin.getSettings().sellFormat) Locale.SOLD_CHEST_FOOTER.send(offlinePlayer.getPlayer(), StringUtils.format(totalEarned)); else Locale.SOLD_CHEST_FOOTER.send(offlinePlayer.getPla
Yeah I tried with !<condition> first, but I thought it's not working because of that and I left it just like that

2021-11-18 10:22 UTC, Faceless0102 commented on src/main/java/com/bgsoftware/wildchests/task/NotifierTask.java
> +                if(!plugin.getSettings().sellFormat) Locale.SOLD_CHEST_FOOTER.send(offlinePlayer.getPlayer(), StringUtils.format(totalEarned)); else Locale.SOLD_CHEST_FOOTER.send(offlinePlayer.getPla
I tried the following:
`Locale.SOLD_CHEST_LINE.send(offlinePlayer.getPlayer(), item.amount, item.itemStack.getType(), (!plugin.getSettings().sellFormat) ? StringUtils.format(item.amountEarned)) : StringUtils.fancyFormat(item.amountEarned));`

I got this error: 
```
C:\Users\Alex\IdeaProjects\WildChests\src\main\java\com\bgsoftware\wildchests\task\NotifierTask.java:51: error: not a statement
                    Locale.SOLD_CHEST_LINE.send(offlinePlayer.getPlayer(), item.amount, item.itemStack.getType(), (!plugin.getSettings().sellFormat) ? StringUtils.format(item.amountEarned)) : StringUtils.fancyFormat(item.amountEarned))
;
```

2021-11-18 13:37 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildchests/task/NotifierTask.java
> +                if(!plugin.getSettings().sellFormat) Locale.SOLD_CHEST_FOOTER.send(offlinePlayer.getPlayer(), StringUtils.format(totalEarned)); else Locale.SOLD_CHEST_FOOTER.send(offlinePlayer.getPla
I will look into that.
Thanks for contributing your time :)

2021-11-18 15:35 UTC, Faceless0102 commented on src/main/java/com/bgsoftware/wildchests/task/NotifierTask.java
> +                if(!plugin.getSettings().sellFormat) Locale.SOLD_CHEST_FOOTER.send(offlinePlayer.getPlayer(), StringUtils.format(totalEarned)); else Locale.SOLD_CHEST_FOOTER.send(offlinePlayer.getPla
You're welcome, I had no issues so far on my live server and the chat is nicely formatted now :)

2021-11-19 12:21 UTC, OmerBenGera commented
I pushed 3 commits, let me know if these don't break anything.
If not, I'll merge.

2021-11-19 12:43 UTC, Superalex0102 commented
![image](https://user-images.githubusercontent.com/41546701/142624648-38f081c3-fd72-4ba2-b542-69686059479b.png)
Nope, it doesn't wanna work now

2021-11-19 12:51 UTC, OmerBenGera commented
My bad, try now

2021-11-19 13:00 UTC, Superalex0102 commented
![image](https://user-images.githubusercontent.com/41546701/142626867-4a6f8ce3-561c-48c2-a152-7fb5946e7a67.png)
Something is still not okay

2021-11-19 13:05 UTC, OmerBenGera commented
> ![image](https://user-images.githubusercontent.com/41546701/142626867-4a6f8ce3-561c-48c2-a152-7fb5946e7a67.png) Something is still not okay

What's not okay if I may ask?

2021-11-19 13:10 UTC, Superalex0102 commented
> > ![image](https://user-images.githubusercontent.com/41546701/142626867-4a6f8ce3-561c-48c2-a152-7fb5946e7a67.png) Something is still not okay
> 
> What's not okay if I may ask?

As you see the values doesn't add up and one of them is $0

2021-11-19 13:10 UTC, Superalex0102 commented
![image](https://user-images.githubusercontent.com/41546701/142628134-fcf91b0c-3d56-451e-9ee0-76d369f83b0c.png)
Another example

2021-11-19 13:26 UTC, OmerBenGera commented
> ![image](https://user-images.githubusercontent.com/41546701/142628134-fcf91b0c-3d56-451e-9ee0-76d369f83b0c.png) Another example

If you disable the sell-format, does it still occur?

2021-11-19 13:32 UTC, Superalex0102 commented
![image](https://user-images.githubusercontent.com/41546701/142631061-29e4468f-91a4-4cea-87a9-294817f5ae1d.png)
I disabled the sell-format and now it adds up correctly

2021-11-19 13:44 UTC, OmerBenGera commented
I detected the issue, check out latest build.

2021-11-19 13:48 UTC, OmerBenGera commented
I mean of course build it yourself and check if it works*

2021-11-19 14:21 UTC, Superalex0102 commented
It works now, nice!

2021-11-19 15:24 UTC, merged