Added transfer-money option, that allows to select which payout metho…
BG-Software-LLC/WildChests pull request #76
Opened 2021-11-28 01:11 UTC by Superalex0102

…d the chest should use!

Hey **Ome_R** again!

I now added a new, custom and awesome chest feature! Now you can select between **Vault** and **SuperiorSkyblock2** as a payout method while using the sell-chest option!

Something I have come across:
In SuperiorSkyblock if you have this enabled:
```
# Should transaction logs of the island bank be saved to database?
# Warning: There may be a lot of transactions, and can increase database.
bank-logs: true
```
The plugin will spam the **database**, I'm asking you how should we fix this and what to implement.

I tested on my live server and it works amazing, no issues at all so far.

I used **switch** if anyone or you would like to add new payout methods in the future!

2021-11-28 05:49 UTC, OmerBenGera requested changes

2021-11-28 05:49 UTC, OmerBenGera commented on API/src/main/java/com/bgsoftware/wildchests/api/objects/data/ChestData.java
> +    String getTransferMoney();
An enum should be used instead of a string.

2021-11-28 05:49 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildchests/Locale.java
> +    public static Locale CHEST_INFO_TRANSFER_MONEY_METHOD = new Locale("CHEST_INFO_TRANSFER_MONEY_METHOD");
Try to think about a better name.

2021-11-28 05:49 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildchests/handlers/SettingsHandler.java
Try to think about a better name.
Something like "deposit-method" would fit better in my opinion.

2021-11-28 05:49 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildchests/objects/data/WChestData.java
> +    public String getTransferMoney() { return transferMoney; }
Dont use one-line methods.

2021-11-28 05:49 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildchests/utils/ChestUtils.java
> +            switch (chest.getData().getTransferMoney().toUpperCase()) {
Instead of a switch-case on the value, make it OOP style.
Create an interface in the hooks package to determine different deposit methods, and the depositPlayer method should use the interface instead of implementing the logic itself.
It should be similar to how the PricesProvider is done. Think about an indicative name for the interface :)

2021-11-28 05:49 UTC, OmerBenGera commented on src/main/resources/config.yml
> +#     Currently supported: SuperiorSkyblock2
Vault is also supported.

2021-11-28 05:49 UTC, OmerBenGera commented on src/main/resources/lang.yml
> +CHEST_INFO_TRANSFER_MONEY_METHOD: '&5 Sell Method&7: &f{0}'
Are you sure its necessary?
This can easily be added to the footer message if people want.. I think it can be removed.

2021-11-28 11:27 UTC, Superalex0102 commented on src/main/java/com/bgsoftware/wildchests/utils/ChestUtils.java
> +            switch (chest.getData().getTransferMoney().toUpperCase()) {
One class for each deposit method?

2021-11-28 11:27 UTC, Superalex0102 commented on src/main/java/com/bgsoftware/wildchests/objects/data/WChestData.java
> +    public String getTransferMoney() { return transferMoney; }
I just copied the same style as the other methods :(

2021-11-28 11:27 UTC, Superalex0102 commented on src/main/java/com/bgsoftware/wildchests/handlers/SettingsHandler.java
Done

2021-11-28 11:27 UTC, Superalex0102 commented on src/main/java/com/bgsoftware/wildchests/Locale.java
> +    public static Locale CHEST_INFO_TRANSFER_MONEY_METHOD = new Locale("CHEST_INFO_TRANSFER_MONEY_METHOD");
Done

2021-11-28 11:43 UTC, Superalex0102 commented on src/main/java/com/bgsoftware/wildchests/utils/ChestUtils.java
> +            switch (chest.getData().getTransferMoney().toUpperCase()) {
One interface for each deposit method?

2021-11-28 16:06 UTC, Superalex0102 commented on src/main/java/com/bgsoftware/wildchests/utils/ChestUtils.java
> +import java.util.*;
I don't know why IntellIj did that

2021-11-28 21:11 UTC, OmerBenGera requested changes

2021-11-28 21:11 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildchests/handlers/SettingsHandler.java
> +                chestData.setDepositMethod(DepositMethod.valueOf(cfg.getString("chests." + name + ".deposit-method")));
No one guarantees the config option will be valid.
An exception can be thrown with invalid input.

2021-11-28 21:11 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildchests/objects/data/WChestData.java
> +    private String depositMethod;
Why are you saving the deposit method as a string?

2021-11-28 21:11 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildchests/objects/data/WChestData.java
> +    public DepositMethod getDepositMethod() {
Missing @Override annotation

2021-11-28 21:11 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildchests/hooks/DepositMethod.java
> +        switch (chest.getData().getDepositMethod()) {
Ypu havent changed anything, you only moved the code to another class.
You should instead make an interface for a BankProvider, and then have each plugin to have a class that implements this interface with the logic for that plugin.
Then, in the ProvidersHandler, save a map of DepositMethod->BankProvider, and when depositMethod is called, it should get the correct BankProvider and run it.
Make sure you think about the scenario that SuperiorSkyblock or Vault are not installed, and therefore their BankProvider xlasses should not be created.

2021-11-29 11:44 UTC, Superalex0102 commented on src/main/java/com/bgsoftware/wildchests/objects/data/WChestData.java
> +    public DepositMethod getDepositMethod() {
The Override annotation is there

2021-11-29 11:44 UTC, Superalex0102 commented on src/main/java/com/bgsoftware/wildchests/objects/data/WChestData.java
> +    private String depositMethod;
Fixed it to DepositMethod

2021-11-29 11:45 UTC, Superalex0102 commented on src/main/java/com/bgsoftware/wildchests/handlers/SettingsHandler.java
> +                chestData.setDepositMethod(DepositMethod.valueOf(cfg.getString("chests." + name + ".deposit-method")));
Done

2021-11-29 11:45 UTC, Superalex0102 commented on API/src/main/java/com/bgsoftware/wildchests/api/objects/DepositMethod.java
> +    SUPERIORSKYBLOCK2
Changed it to Vault, SuperiorSkyblock2

2021-11-29 11:45 UTC, Superalex0102 commented on src/main/java/com/bgsoftware/wildchests/hooks/DepositMethod.java
> +        switch (chest.getData().getDepositMethod()) {
Sorry I must misunderstood what you meant, gonna fix it today

2021-12-03 12:40 UTC, merged